name: CMake Build

on: 
  # push代码时触发workflow
  push:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - 'LICENSE'
        - '.gitignore'
        - 'README.md'
        - 'README_en.md'
        - 'resource/**'
        - 'translations/**'
        - 'docs/**'
  pull_request:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - 'LICENSE'
        - '.gitignore'
        - 'README.md'
        - 'README_en.md'
        - 'resource/**'
        - 'translations/**'
        - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        qt_ver: 
          - 6.4.2
        build_type:
          - "Release"
        generators:
          - "Ninja"

    steps:
      - name: Install dependencies on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install ninja mpv
          ninja --version
          cmake --version
          clang --version

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          install-deps: 'true'
          modules: 'qt5compat addons.qtnetworkauth addons.qtmultimedia addons.qtimageformats'
          cache: 'true'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure macos
        if: startsWith(matrix.os, 'macos')
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
        shell: bash
        run: |
          cmake \
            -S . \
            -B ./build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -G "${{ matrix.generators }}" \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir
      - name: Build
        shell: bash
        run: |
          cmake --build ./build --config ${{ matrix.build_type }}
          