name: QMake Build

on: 
  # push代码时触发workflow
  push:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - 'doc'
        - 'mac'
        - '.clang-format'
        - '.gitignore'
        - 'LICENSE'
        - 'README*'
  pull_request:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - 'doc'
        - 'mac'
        - '.clang-format'
        - '.gitignore'
        - 'LICENSE'
        - 'README*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        qt_ver: 
          - 6.5.0

    steps:
      - name: Install dependencies on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install ninja mpv
          ninja --version
          cmake --version
          clang --version

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          install-deps: 'true'
          modules: 'qt5compat addons.qtnetworkauth addons.qtmultimedia addons.qtimageformats'
          cache: 'true'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: build macos
        if: startsWith(matrix.os, 'macos')
        run: |
          qmake
          make -j4
