name: QMake Build

on: 
  # push代码时触发workflow
  push:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - '.github/workflows/cmake.yml'
        - '.github/workflows/readme.yml'
        - 'doc/**'
        - 'packaging/**'
        - '.clang*'
        - '.gitignore'
        - 'LICENSE'
        - 'README*'
  pull_request:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - '.github/workflows/cmake.yml'
        - '.github/workflows/readme.yml'
        - 'doc/**'
        - 'packaging/**'
        - '.clang*'
        - '.gitignore'
        - 'LICENSE'
        - 'README*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        qt_ver: 
          - 6.6.2

    steps:
      - name: Install dependencies on macos
        if: startsWith(matrix.os, 'macos')
        shell: bash
        run: |
          brew install ninja mpv
          ninja --version
          cmake --version
          clang --version

      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install mpv libmpv-dev ninja-build
          ninja --version
          cmake --version
          gcc --version

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          install-deps: 'true'
          modules: 'qt5compat qtnetworkauth qtmultimedia qtimageformats'
          cache: 'true'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: msvc-build
        if: startsWith(matrix.os, 'windows')
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake
          nmake
      - name: build macos or ubuntu
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          qmake
          make -j4
